// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD1D9D2ioapdsaXjKZGqeJ_riXVJXZX6E',
    appId: '1:599549183484:web:1936f77ceea123c1d6de79',
    messagingSenderId: '599549183484',
    projectId: 'admin-site-4b122',
    authDomain: 'admin-site-4b122.firebaseapp.com',
    storageBucket: 'admin-site-4b122.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPpQo7PtM8e0eY3HU3205XOOdg2S4kOeE',
    appId: '1:599549183484:android:b01264e971e206bed6de79',
    messagingSenderId: '599549183484',
    projectId: 'admin-site-4b122',
    storageBucket: 'admin-site-4b122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbgk8GT2ZNO5u46rZxfC_m6kkOCLM1Hgk',
    appId: '1:599549183484:ios:ece6fdb9471f4a77d6de79',
    messagingSenderId: '599549183484',
    projectId: 'admin-site-4b122',
    storageBucket: 'admin-site-4b122.firebasestorage.app',
    iosBundleId: 'com.example.locUl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbgk8GT2ZNO5u46rZxfC_m6kkOCLM1Hgk',
    appId: '1:599549183484:ios:ece6fdb9471f4a77d6de79',
    messagingSenderId: '599549183484',
    projectId: 'admin-site-4b122',
    storageBucket: 'admin-site-4b122.firebasestorage.app',
    iosBundleId: 'com.example.locUl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD1D9D2ioapdsaXjKZGqeJ_riXVJXZX6E',
    appId: '1:599549183484:web:9d66a4bcd52f3284d6de79',
    messagingSenderId: '599549183484',
    projectId: 'admin-site-4b122',
    authDomain: 'admin-site-4b122.firebaseapp.com',
    storageBucket: 'admin-site-4b122.firebasestorage.app',
  );
}
