name: loc_ul
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cloud_firestore: ^5.0.1        # Firestore
  shared_preferences: ^2.2.2     # cache simple (clé/valeur)
  provider: ^6.1.1               # MVVM / écoute d’état
  firebase_core: ^3.13.0
  firebase_auth: ^5.0.0          # ajout de firebase_auth
  http: 1.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
